### ISSUE TITLE
It's not clear what the overall goal of this package is

### ISSUE THREAD

**Issue by TheXRMonk** [DataDog/dd-sdk-unity#103]
### Question

Is it supposed to cover all use cases with DataDog from a Unity specific implementation?

- Right now it seem lack luster if the only thing it can do is automate views and send logs. 
- What about metrics? Etc. 
- What is the scope of this?
- Should we integrate other packages or methods (c# or custom HTTPS) for filling out missing features?

**Comment by TheXRMonk** [comment]
~~Also, how does one change environment?~~
Ah, through the project settings 👍

**Comment by TheXRMonk** [comment]
Also adding; it would be beneficial to be able to change the environment at runtime. Our pipeline takes the binary through different release channels, which correlate to our environments, and is then lastly promoted to production. Currently, there's no way to "promote" a build if it has the environment hardcoded. 

Also, maybe add documentation for the RUM methods, like "StartResource". 👍

**Comment by fuzzybinary** [comment]
Hi @TheXRMonk , sorry for the delay in response:

> Is it supposed to cover all use cases with DataDog from a Unity specific implementation?

Eventually, yes, the use cases covered by the SDK will expand. This is still very early days and we're focusing on the Logs and Real User Monitoring products, as our other Mobile SDKs do.

> * Right now it seem lack luster if the only thing it can do is automate views and send logs.

While those are the only things it can do automatically, the full suite of RUM functionality is available to you through manual methods, including action tracking, crash tracking, and distributed tracing of network requests.  The SDK also provides system information (OS version, memory usage, network quality), and caches and batches requests.  All of these features are inherited form the underlying Android and iOS SDKs.

> * What about metrics? Etc.

Metrics would need a feature request. You'll need to expand on the etc though.

> * What is the scope of this?

Right now, mobile Unity applications that want to send data to Logs or RUM. This will expand over time.

> * Should we integrate other packages or methods (c# or custom HTTPS) for filling out missing features?

If there's a specific feature you're missing, please reach out and we'll see what we can do to help you.

> Also adding; it would be beneficial to be able to change the environment at runtime.

We're looking into this, as well as changing other variables as well. The environment and service really need to be set during initialization in order to prevent inconsistent data, and we want to initialize as soon as we can to support catching crashes on launch.  But, we're looking at was to have both of these work properly.

> Also, maybe add documentation for the RUM methods, like "StartResource".

This is still early days, so some documentation maybe missing from the Datadog site. We're working on it. In the meantime, the methods on the interface are documented in C#.
https://github.com/DataDog/dd-sdk-unity/blob/6a98058a4e32b803b03b4ae2c551ba87ccd4d017/packages/Datadog.Unity/Runtime/Rum/DdRum.cs#L138

**Comment by TheXRMonk** [comment]
> Hi @TheXRMonk , sorry for the delay in response:
> 
> > Is it supposed to cover all use cases with DataDog from a Unity specific implementation?
> 
> Eventually, yes, the use cases covered by the SDK will expand. This is still very early days and we're focusing on the Logs and Real User Monitoring products, as our other Mobile SDKs do.
> 
> > * Right now it seem lack luster if the only thing it can do is automate views and send logs.
> 
> While those are the only things it can do automatically, the full suite of RUM functionality is available to you through manual methods, including action tracking, crash tracking, and distributed tracing of network requests. The SDK also provides system information (OS version, memory usage, network quality), and caches and batches requests. All of these features are inherited form the underlying Android and iOS SDKs.
> 
> > * What about metrics? Etc.
> 
> Metrics would need a feature request. You'll need to expand on the etc though.
> 
> > * What is the scope of this?
> 
> Right now, mobile Unity applications that want to send data to Logs or RUM. This will expand over time.
> 
> > * Should we integrate other packages or methods (c# or custom HTTPS) for filling out missing features?
> 
> If there's a specific feature you're missing, please reach out and we'll see what we can do to help you.
> 
> > Also adding; it would be beneficial to be able to change the environment at runtime.
> 
> We're looking into this, as well as changing other variables as well. The environment and service really need to be set during initialization in order to prevent inconsistent data, and we want to initialize as soon as we can to support catching crashes on launch. But, we're looking at was to have both of these work properly.
> 
> > Also, maybe add documentation for the RUM methods, like "StartResource".
> 
> This is still early days, so some documentation maybe missing from the Datadog site. We're working on it. In the meantime, the methods on the interface are documented in C#.
> 
> https://github.com/DataDog/dd-sdk-unity/blob/6a98058a4e32b803b03b4ae2c551ba87ccd4d017/packages/Datadog.Unity/Runtime/Rum/DdRum.cs#L138

Thanks for the detailed response! It's very insightful, and I look forward to following the improvements! 

* Is there a public roadmap?

It's still early days for our team so we need to discover all the features and best practices for setting them up. 
* For changing environment at runtime: It would be beneficial to have an "invalid" environment and stack up messages (like the SDK does when the user's Permission is pending, and then send once granted). 

Again, thank you!

**Comment by fuzzybinary** [comment]
> Is there a public roadmap?

Not at the moment, sorry. If you have a specific need or want a feature prioritized, reach out to Datadog sales or support. They'll also be able to walk you through the features and best practices for setting up Datadog.

> For changing environment at runtime: It would be beneficial to have an "invalid" environment and stack up messages (like the SDK does when the user's Permission is pending, and then send once granted).

This is one option yes, but this will likely be part of a larger feature set we're investigating.

If you need to distinguish between environments, one way to do this is to instead use a Custom Attribute by calling `AddAttribute` on RUM or your Logger. You can then use this instead of the built in `env` tag on your queries in RUM or Logs.  We recognize this is not ideal, but it's a usable workaround.
